apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
    spec:
      containers:
        - name: result-app
          image: rumeysakdogan/phonebook-resultserver
          ports:
          - containerPort: 80
          env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-admin-password
          envFrom:
          - configMapRef:
              name: servers-configmap


