---
# tasks file for postgre
  - name: create build directory
    file:
      path: "{{ postgre_container }}"
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: copy the sql script
    copy:
      src: init.sql   # write only file name
      dest: "{{ postgre_container }}"

  - name: copy the Dockerfile
    copy:
      src: Dockerfile   # write only file name
      dest: "{{ postgre_container }}"

  - name: remove {{ container_name }} container and {{ image_name }} if exists
    shell: "docker ps -q --filter 'name={{ container_name }}' && docker stop {{ container_name }} && docker rm -fv {{ container_name }} && docker image rm -f {{ image_name }} || echo 'Not Found'"

  - name: build container image
    docker_image:
      name: "{{ image_name }}"
      build:
        path: "{{ postgre_container }}"
      source: build
      state: present

  - name: Launch postgresql docker container
    docker_container:
      name: "{{ container_name }}"
      image: "{{ image_name }}"
      state: started
      ports: 
      - "5432:5432"
      env:
        POSTGRES_PASSWORD: "Pp123456789"
      volumes:
        - /db-data:/var/lib/postgresql/data
